List<String> questionList = [
  'I prefer making lists rather than relying on my memory.',
  'I am skeptical about things and don’t trust easily.',
  'I prefer spending time with others rather than spending time alone.',
  'I accept things the way they are and am easily satisfied with the way things are.',
  'I prefer cleanliness and keeping things in their right place.',
  'I think having a mechanical mind and being called robotic is an insult.',
  'I think I am more energetic than mellow.',
  'I prefer taking multiple-choice tests, instead of essay answers.',
  'I don’t mind being messy instead of being organized.',
  'I easily get disheartened by cruel words.',
  'I prefer working in groups rather than working alone.',
  'I prefer focusing on the present rather than mapping the future.',
  'I like planning everything in advance rather than at the last minute.',
  'I’d rather have people respect me first than love me.',
  'Parties tend to drain me out instead of firing me up.',
  'I usually fit in a new group of people easily.',
  'I prefer keeping my options open instead of committing to something.',
  'I would rather be good at fixing things than fixing people.',
  'In a conversation, I tend to talk more and listen less.',
  'When describing an event I tell people what happened rather than tell them what it meant.',
  'I prefer finishing my work right away and don\'t procrastinate.',
  'I follow my heart rather than my head.',
  'I prefer staying at home over going out.',
  'I prefer the big picture over the details.',
  'I like to improvise instead of preparing.',
  'I prefer to base morality on justice rather than compassion.',
  'I find it difficult to yell very loudly even if a person is far away.',
  'I am more theoretical than empirical.',
  'I\'m a workaholic and I tend to bury myself with work and rarely find time for myself.',
  'I struggle with expressing my emotions.',
  'I like performing and speaking in front of other people.',
  'I like to know the Who, What and When behind something instead of the Why.',

];
List radioValue = [
  -5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,-5,
];

